worldWidth=2000
worldHeight=720
platform.count=3
platform.0=2000,60,0,550,METAL
platform.1=400,32,800,450,GRASS
platform.2=400,32,1200,350,GRASS
enemy.count=1
enemy.0=BAZOOKA_BOSS,1000,500
item.count=0
minScore=0
nextLevel=null
exitZone.x=1940
exitZone.w=60
background=Cave.png